version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: tax_office
      MYSQL_USER: user
      MYSQL_PASSWORD: pass